version: "3.4"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - 3000:3000
    links:
      - graphql:api
  graphql:
    build:
      context: ./
      dockerfile: Dockerfile.graphql
    ports:
      - 9002:9002
