version: "3"
services:
  frontend:
    build:
      context: ./
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - 3000:3000
    env_file:
      - .env
    links:
      - graphql
  graphql:
    build:
      context: ./
      dockerfile: Dockerfile-graphql
    ports:
      - 9002:9002
